package com.bolehunt.gene.domain;

import java.util.Date;
import java.util.UUID;

import org.joda.time.DateTime;

import com.bolehunt.gene.common.Constant;
import com.bolehunt.gene.common.Constant.VerifyTokenType;

public class VerifyToken {
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_token.id
     *
     * @mbggenerated Thu Jun 11 21:50:00 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_token.user_id
     *
     * @mbggenerated Thu Jun 11 21:50:00 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_token.token
     *
     * @mbggenerated Thu Jun 11 21:50:00 CST 2015
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_token.token_type
     *
     * @mbggenerated Thu Jun 11 21:50:00 CST 2015
     */
    private Integer tokenType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_token.expiry_date
     *
     * @mbggenerated Thu Jun 11 21:50:00 CST 2015
     */
    private Date expiryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_token.verified
     *
     * @mbggenerated Thu Jun 11 21:50:00 CST 2015
     */
    private Integer verified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_token.id
     *
     * @return the value of verify_token.id
     *
     * @mbggenerated Thu Jun 11 21:50:00 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_token.id
     *
     * @param id the value for verify_token.id
     *
     * @mbggenerated Thu Jun 11 21:50:00 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_token.user_id
     *
     * @return the value of verify_token.user_id
     *
     * @mbggenerated Thu Jun 11 21:50:00 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_token.user_id
     *
     * @param userId the value for verify_token.user_id
     *
     * @mbggenerated Thu Jun 11 21:50:00 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_token.token
     *
     * @return the value of verify_token.token
     *
     * @mbggenerated Thu Jun 11 21:50:00 CST 2015
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_token.token
     *
     * @param token the value for verify_token.token
     *
     * @mbggenerated Thu Jun 11 21:50:00 CST 2015
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_token.token_type
     *
     * @return the value of verify_token.token_type
     *
     * @mbggenerated Thu Jun 11 21:50:00 CST 2015
     */
    public Integer getTokenType() {
        return tokenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_token.token_type
     *
     * @param tokenType the value for verify_token.token_type
     *
     * @mbggenerated Thu Jun 11 21:50:00 CST 2015
     */
    public void setTokenType(Integer tokenType) {
        this.tokenType = tokenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_token.expiry_date
     *
     * @return the value of verify_token.expiry_date
     *
     * @mbggenerated Thu Jun 11 21:50:00 CST 2015
     */
    public Date getExpiryDate() {
        return expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_token.expiry_date
     *
     * @param expiryDate the value for verify_token.expiry_date
     *
     * @mbggenerated Thu Jun 11 21:50:00 CST 2015
     */
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_token.verified
     *
     * @return the value of verify_token.verified
     *
     * @mbggenerated Thu Jun 11 21:50:00 CST 2015
     */
    public Integer getVerified() {
        return verified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_token.verified
     *
     * @param verified the value for verify_token.verified
     *
     * @mbggenerated Thu Jun 11 21:50:00 CST 2015
     */
    public void setVerified(Integer verified) {
        this.verified = verified;
    }
    
   
    
    private static final int DEFAULT_EXPIRY_TIME_IN_MINS = 60 * 24; //24 hours
    
    public VerifyToken() {
        super();
        this.token = UUID.randomUUID().toString();
        this.verified = Constant.TokenVerifyType.NOT_VERIFIED.getValue(); //set not verified from start
        this.expiryDate = calculateExpiryDate(DEFAULT_EXPIRY_TIME_IN_MINS);
    }

    public VerifyToken(int userId, VerifyTokenType tokenType, int expirationTimeInMinutes) {
        this();
        this.userId = userId;
        this.tokenType = tokenType.getValue();
        this.expiryDate = calculateExpiryDate(expirationTimeInMinutes);
    }
    
    private Date calculateExpiryDate(int expiryTimeInMinutes) {
        DateTime now = new DateTime();
        return now.plusMinutes(expiryTimeInMinutes).toDate();
    }
    
    public boolean isTokenVerified(){
    	return this.verified.equals(Constant.TokenVerifyType.VERIFIED.getValue()) ? true : false;
    }
    
    public boolean hasExpired() {
        DateTime tokenDate = new DateTime(getExpiryDate());
        return tokenDate.isBeforeNow();
    }
}